name: Terraform Security Scan

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/environments/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
